name: 'work-1'
...
jobs:
  ...
  deploy:
    name: 쿠버네티스 배포
    runs-on: ubuntu-latest
    steps:
    - uses: azure/k8s-set-context@v2
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBE_CONFIG }}
    - run: |
        kubectl get all
